mdedit:
  # Toolbar configuration for usernotes.
  #
  # It omits buttons for emoji and image even though they are enabled
  # (they are rarely useful here, but user can still add them manually).
  #
  usernote:
    bold: true
    italic: true
    link: true
    separator1:
      priority: 45
    ol: true
    ul: true
    separator3:
      priority: 105
    help: true
