menus:
  common:
    navbar:
      tracker:
        to: users.tracker
        autoselect: false
        priority: 10
  admin:
    navbar:
      users:
        to: admin.users.usergroups.index
        submenu:
          members:
            to: admin.users.members.search
          usergroups:
            to: admin.users.usergroups.index
