router:
  http.get:
    users.tracker:
      "/tracker": ~

    users.member:
      "/member{user_hid}":
        user_hid:
          match: /\d+/
          type: 'integer'

    users.dialogs_root:
      "/member{user_hid}/dialogs(/{dialog_id})":
        user_hid:
          match: /\d+/
          type: 'integer'
        dialog_id:
          match: /[0-9a-f]{24}/

    users.dialogs_root.unsubscribe.index:
      "/unsubscribe/dialogs": ~

    users.dialogs_root.unsubscribe.done:
      "/unsubscribe/dialogs/done": ~

    users.dialog:
      "/dialog/{dialog_id}(/{message_id})":
        dialog_id:
          match: /[0-9a-f]{24}/
        message_id:
          match: /[0-9a-f]{24}/

    users.infraction_ask_about:
      "/infraction_ask_about/{infraction_id}":
        infraction_id:
          match: /[0-9a-f]{24}/

    users.settings.general:
      "/settings": ~

    users.settings.about:
      "/settings/about": ~

    users.settings.ignore:
      "/settings/ignore": ~

    users.settings.location:
      "/settings/location": ~

    users.subscriptions.index:
      "/tracker/subscriptions": ~

    users.albums_root:
      "/member{user_hid}/albums":
        user_hid:
          match: /\d+/
          type: 'integer'

    users.mod_notes:
      "/member{user_hid}/mod_notes":
        user_hid:
          match: /\d+/
          type: 'integer'

    users.album:
      "/member{user_hid}/album/{album_id}(/{media_id})":
        user_hid:
          match: /\d+/
          type: 'integer'
        album_id:
          match: /[0-9a-f]{24}/
        media_id:
          match: /[0-9a-f]{24}/
      "/member{user_hid}/albums/all(/{media_id})":
        user_hid:
          match: /\d+/
          type: 'integer'
        media_id:
          match: /[0-9a-f]{24}/

    users.activity:
      "/member{user_hid}/activity":
        user_hid:
          match: /\d+/
          type: 'integer'
      "/member{user_hid}/activity/{type}(/{start})":
        user_hid:
          match: /\d+/
          type: 'integer'
        type:
          match: /\w+/
        start:
          match: /[0-9a-f]{24}/

    users.bookmarks:
      "/member{user_hid}/bookmarks(/{start})":
        user_hid:
          match: /\d+/
          type: 'integer'
        start:
          match: /[0-9a-f]{24}/

    users.album.edit:
      "/member{user_hid}/album/{album_id}/edit":
        user_hid:
          match: /\d+/
          type: 'integer'
        album_id:
          match: /[0-9a-f]{24}/

    users.media:
      "/member{user_hid}/media/{media_id}":
        user_hid:
          match: /\d+/
          type: 'integer'
        media_id:
          match: /[0-9a-f]{24}/

    users.auth.login.show:
      "/auth/login(/{redirect_id})":
        redirect_id: /[0-9a-f]{24}/

    users.auth.login.by_email_exec:
      "/auth/login/by_email/{secret_key}":
        secret_key: /[0-9a-f]+/

    users.auth.login.by_email_show:
      "/auth/login/by_email/sent": ~

    users.auth.reset_password.request_show:
      "/auth/reset": ~

    users.auth.reset_password.request_done_show:
      "/auth/reset/sent": ~

    users.auth.reset_password.change_show:
      "/auth/reset/{secret_key}":
        secret_key: /[0-9a-f]+/

    users.auth.reset_password.change_done_show:
      "/auth/reset/done":

    users.auth.register.show:
      "/auth/register": ~

    users.auth.register.activate_show:
      "/auth/register/done": ~

    users.auth.register.activate_exec:
      "/auth/register/activate/{secret_key}":
        secret_key: /[0-9a-f]+/

    users.auth.register.activate_done:
      "/auth/register/activate/done": ~

    users.auth.oauth.callback:
      "/auth/oa/{provider}":
        provider: /[0-9a-zA-Z]+/

    users.auth.oauth.error_show:
      "/auth/oa/error": ~

    # Admin panel routes
    admin.users.usergroups.index:
      "/usergroups": ~

    admin.users.usergroups.new:
      "/usergroups/new": ~

    admin.users.usergroups.edit:
      "/usergroups/edit/{_id}":
        _id: /[0-9a-f]{24}/

    admin.users.members.search:
      "/members/search": ~

    admin.users.members.edit:
      "/members/edit/{user_hid}":
        user_hid:
          match: /\d+/
          type: 'integer'
